sudo: false

language: cpp

os:
  - linux
  - osx

env:
  # code analysis
  - TASK=lint
  # build mxnet.so with CUDA
  - TASK=build
  # run tests/cpp
  - TASK=cpp_test
  # run tests/python
  - TASK=python_test
  - TASK=r_test
  - TASK=julia JULIA_VER=0.4
  - TASK=scala_test

  # TODO, R test, distributed test, clang, more g++ versions

matrix:
  exclude:
    - os: osx
      env: TASK=lint
    - os: osx
      env: TASK=julia JULIA_VER=0.4
    - os: linux
      env: TASK=r_test

# dependent apt packages
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - doxygen
      - wget
      - git
      - libcurl4-openssl-dev
      - unzip
      - libatlas-dev
      - libopencv-dev
      - gcc-4.8
      - g++-4.8
      - python-numpy
      - python-nose
      - python3-numpy
      - python3-dev
      - python3-nose
      - graphviz

before_install:
  - export NVCC_PREFIX=${HOME}
  - source dmlc-core/scripts/travis/travis_setup_env.sh
  - export PYTHONPATH=${PYTHONPATH}:${PWD}/python
  - export MAVEN_SKIP_RC=true
  - export MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=256m -XX:-UseGCOverheadLimit -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC"

install:
  - source tests/travis/setup.sh

script:
  - tests/travis/run_test.sh

cache:
  directories:
    - ${HOME}/.cache/usr

before_cache:
  - dmlc-core/scripts/travis/travis_before_cache.sh

after_failure:
  - tests/travis/travis_after_failure.sh

notifications:
# Emails are sent to the committer's git-configured email address by default,
  email:
    on_success: change
    on_failure: always
  #slack: dmlc:NmroCzntCiWOuxUZpii40USd
